version: "3"

services:
  nginx:
    image: nginx
    volumes:
      - ./deployment/flaskapp.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - app

  elastic:
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
  app:
    build: .
    environment:
      - ELASTIC_HOST=elastic
    depends_on:
      - elastic

