version: "3.6"

services:
  nginx:
    image: nginx
    volumes:
      - ./deployment/flaskapp.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - app
  elastic:
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
  app:
    build: .
    environment:
      - FLASK_APP=src/dss
      - ELASTIC_HOST=elastic
      - MYSQL_HOST=mysql
    env_file:
      - mysql.env
    # for development reason
#    volumes:
#      - ./src:/app/src
    depends_on:
      - elastic
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
    - ./dbdata:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
    env_file:
      - mysql.env
